# Site settings
email: marko.raatikka@gmail.com
baseurl: "/enli.fi"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Enli
description: > # this means to ignore newlines until "url:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: ""
twitter_username: mraatikka
default_img:

# Profile settings
name:
profile_img:
profile:
social:
  github:

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-feed,jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
